id = "wasp"
name = "Wasp Language Support"
version = "0.0.1"
schema_version = 1
authors = ["Stephen Buchanan <webtvmaster@gmail.com>"]
description = "Syntax highlighting support for the Wasp DSL (.wasp files)"
repository = "https://github.com/anselanza/wasp-lang-zed"

[grammars.wasp]
repository = "https://github.com/anselanza/tree-sitter-wasp"
rev = "main"
